### ISSUE TITLE
Where to find good map tiles for offline

### ISSUE THREAD

**Issue by Inateno** [webglearth/webglearth2-offline#3]
Hi,

First, very nice project it's fast and well designed I like it and I want to use it for a project in my company.
We need this project to be 100% offline (which is great because it's exactly hat this repo does).

My problem now is to find good tiles offline to download because in the repository zoom goes only up to 5 (I know it's a big amount of data).
MapTiler doesn't give maps sources, and I've been looking a lot of sources and cannot find anything working like the same mapping so I wanna to ask where did you find your map, maybe you know a good way to do this ?
(I still can load a online app and save from cache but this will take a lot of time and probably not from open source).

**Comment by klokan** [comment]
See our project http://osm2vectortiles.org/ where you can download a complete world map - every single street and house on the world. It is ~65 GB of data to host - and there is a free software which turns it into raster map tiles with a look&feel of your choice. These raster maps are then usable in WebGL Earth directly.

If you need satellite / aerial data - then get MapTiler and download NASA Blue Marble data, Landsat7, and NAIP (for USA) + UHR.

We can assist with any of these processes as part of a consulting contract.

**Comment by Inateno** [comment]
Great! Thank you :)
